ALTER TABLE SRN_TBL_NOTA  
MODIFY (NUM_PARCIAL_I DECIMAL(2, 2) );

ALTER TABLE SRN_TBL_NOTA  
MODIFY (NUM_PARCIAL_II DECIMAL(2, 2) );

ALTER TABLE SRN_TBL_NOTA  
MODIFY (NUM_PARCIAL_III DECIMAL(2, 2) );

ALTER TABLE SRN_TBL_NOTA  
MODIFY (NUM_NOTA_FINAL DECIMAL(3, 2) );
