--SRN_TBL_NOTA
ALTER TABLE SRN_TBL_NOTA  
MODIFY (NUM_PARCIAL_I DECIMAL(2, 2) );

ALTER TABLE SRN_TBL_NOTA  
MODIFY (NUM_PARCIAL_II DECIMAL(2, 2) );

ALTER TABLE SRN_TBL_NOTA  
MODIFY (NUM_PARCIAL_III DECIMAL(2, 2) );

ALTER TABLE SRN_TBL_NOTA  
MODIFY (NUM_NOTA_FINAL DECIMAL(3, 2) );

--SRN_TBL_MATERIA_USUARIO
ALTER TABLE SRN_TBL_MATERIA_USUARIO 
ADD (NUM_COD_DOCENTE NUMBER(12,0));

ALTER TABLE SRN_TBL_MATERIA_USUARIO
ADD CONSTRAINT PK_TBL_MATERIA_USUR_DOCENTE FOREIGN KEY(NUM_COD_DOCENTE)
REFERENCES SRN_TBL_USUARIO(NUM_ID_USUARIO)
DISABLE;
